# The port to listen to for HTTP requests
server:
    port: 9000
    host: "::1"

scan:
    # The script that will be given a file as its first parameter
    script: './example.sh'
    # The temporary directory to use
    tempDirectory: '/tmp'
    # The base URL of the Home Server to download media from
    baseUrl: 'https://matrix.org'

# Optional. A command to execute when unlinking files from the file
# system instead of using node's fs.unlink. When executed, the first
# argument to the command will be the path of the file being
# removed.
#
# altRemovalCmd: 'rm'
